language: java
jdk:
  - openjdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -f $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - wget -O codacy.sh https://coverage.codacy.com/get.sh
  - chmod +x codacy.sh
script:
  - ./gradlew build jacocoTestReport
after_success:
  - ./codacy.sh