version: 0.2

phases:

  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build --debug
      - sam package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
