AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"


Parameters:
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain

Resources:

  NvaDoiFunctionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn
      EndpointConfiguration: Regional
      Models:
        DoiLookup:
          type: object
          required:
            - doi_url
          properties:
            doi_url:
              type: string

  NvaDoiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: no.unit.nva.doi.FetchDoiMetadata::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          AllowOrigin: '*'
      Events:
        NvaDoi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Auth:
              Authorizer: MyCognitoAuthorizer
            Path: /
            Method: post
            RestApiId: !Ref NvaDoiFunctionApi
            BinaryMediaTypes:
              - 'application~1vnd.citationstyles.csl+json'
              - 'application~1vnd.datacite.datacite+json'
              - 'application~1vnd.datacite.datacite+xml'
            RequestModel:
              Model: DoiLookup
              Required: true

  NvaDoiFunctionBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref NvaDoiFunctionApi
      Stage: !Ref NvaDoiFunctionApi.Stage

